spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  http:
    encoding:
      charset: UTF-8
      enabled: true

logging:
  level:
    org.springframework.web: info

server:
  max-http-header-size: 8KB
  tomcat:
    max-http-post-size: 1MB
    max-connections: 10000
  servlet:
    session:
      cookie:
        secure: true

security:
  oauth2:
    client:
      resource:
        user-info-uri: ${vcap.services.athena-sso.credentials.auth_domain}/userinfo
