---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: latest

inputs:
- name: src-repo
- name: pipeline-repo

outputs:
- name: build-output

caches:
- path: .gradle/
- path: src-repo/node_modules/

params:

  # Credhub
  NEXUS_USERNAME: ((aoc_ad_service.username))
  NEXUS_PASSWORD: ((aoc_ad_service.password))

  # Other
  NEXUS_URL:

run:
  path: pipeline-repo/scripts/build-snapshot.sh
